#!/bin/sh
#
#       /etc/rc.d/init.d/imgdrop
#
#       Runs the imgdrop Service.
#       
#
# chkconfig:   - 85 15 
#

### BEGIN INIT INFO
# Provides:          imgdrop
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start imgdrop at boot time.
# Description:       Control imgdrop.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# Default values

NAME=imgdrop
IMGDROP_HOME=/opt/imgdrop
IMGDROP_PATH=${IMGDROP_HOME}/$NAME
IMGDROP_USER=root
SERVICENAME="ImageDrop web app"
LOCKFILE=/var/lock/subsys/${NAME}
LOGPATH=${IMGDROP_HOME}/log
LOGFILE=${LOGPATH}/${NAME}.log
RETVAL=0

# Read configuration from /etc/sysconfig/gogs to override defaults
[ -r /etc/sysconfig/$NAME ] && . /etc/sysconfig/$NAME

# Don't do anything if nothing is installed
[ -x ${IMGDROP_PATH} ] || exit 0
# exit if logpath dir is not created.
[ -x ${LOGPATH} ] || exit 0

DAEMON_OPTS="--check $NAME"

# Set additional options, if any
[ ! -z "$IMGDROP_USER" ] && DAEMON_OPTS="$DAEMON_OPTS --user=${IMGDROP_USER}"

start() {
  cd ${IMGDROP_HOME}
  echo -n "Starting ${SERVICENAME}: "
  daemon $DAEMON_OPTS "${IMGDROP_PATH} > ${LOGFILE} 2>&1 &"
  RETVAL=$?
  echo
  [ $RETVAL = 0 ] && touch ${LOCKFILE}
        
  return $RETVAL
}

stop() {
  cd ${IMGDROP_HOME}
        echo -n "Shutting down ${SERVICENAME}: "
        killproc ${NAME}
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && rm -f ${LOCKFILE} 
}

case "$1" in
    start)
        status ${NAME} > /dev/null 2>&1 && exit 0
        start
        ;;
    stop)
        stop
        ;;
    status)
        status ${NAME}
        ;;
    restart)
        stop
        start
        ;;
    reload)
        stop
        start
        ;;
    *)
        echo "Usage: ${NAME} {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL