#!/bin/sh
#
#       /etc/rc.d/init.d/imgproxy
#
#       Runs the imgproxy Service.
#       
#
# chkconfig:   - 85 15 
#

### BEGIN INIT INFO
# Provides:          imgproxy
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start imgproxy.
# Description:       Control imgproxy.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# Default values

NAME=imageproxy
IMGPROXY_HOME=$GOPATH
IMGPROXY_PATH=$GOPATH/bin/$NAME
IMGPROXY_USER=root
IMGPROXY_OPTIONS="-addr localhost:4593 -whitelist img.nimbus.com.tw,i1.51hosting.com -cache /var/cache/imgproxy"
SERVICENAME="ImageProxy web app"
LOCKFILE=/var/lock/subsys/${NAME}
LOGPATH=/var/log
LOGFILE=${LOGPATH}/${NAME}.log
RETVAL=0

# Read configuration from /etc/sysconfig/gogs to override defaults
[ -r /etc/sysconfig/$NAME ] && . /etc/sysconfig/$NAME

# Don't do anything if nothing is installed
[ -x ${IMGPROXY_PATH} ] || exit 0
# exit if logpath dir is not created.
[ -x ${LOGPATH} ] || exit 0

DAEMON_OPTS="--check $NAME"

# Set additional options, if any
[ ! -z "$IMGPROXY_USER" ] && DAEMON_OPTS="$DAEMON_OPTS --user=${IMGPROXY_USER}"

start() {
  cd ${IMGPROXY_HOME}
  echo -n "Starting ${SERVICENAME}: "
  daemon $DAEMON_OPTS "${IMGPROXY_PATH} ${IMGPROXY_OPTIONS}> ${LOGFILE} 2>&1 &"
  RETVAL=$?
  echo
  [ $RETVAL = 0 ] && touch ${LOCKFILE}
        
  return $RETVAL
}

stop() {
  cd ${IMGPROXY_HOME}
        echo -n "Shutting down ${SERVICENAME}: "
        killproc ${NAME}
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && rm -f ${LOCKFILE} 
}

case "$1" in
    start)
        status ${NAME} > /dev/null 2>&1 && exit 0
        start
        ;;
    stop)
        stop
        ;;
    status)
        status ${NAME}
        ;;
    restart)
        stop
        start
        ;;
    reload)
        stop
        start
        ;;
    *)
        echo "Usage: ${NAME} {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL